// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Entities;

#nullable disable

namespace SchoolManagement.Migrations
{
    [DbContext(typeof(TimeSheetDbContext))]
    partial class TimeSheetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("SchoolManagement.Entities.AttenStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TimeShift")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("attens");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DptManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("DptName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DptPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TimeShift")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SchoolManagement.Entities.ScoreStudent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("BigData")
                        .HasColumnType("REAL");

                    b.Property<double>("CShap")
                        .HasColumnType("REAL");

                    b.Property<double>("English")
                        .HasColumnType("REAL");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Java")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Python")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("average")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("scoreStudents");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Saray")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserAccountUeserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountUeserAccountId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolManagement.Entities.UeserAccount", b =>
                {
                    b.Property<int>("UeserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UeserAccountId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("SchoolManagement.Entities.AttenStudent", b =>
                {
                    b.HasOne("SchoolManagement.Entities.Student", null)
                        .WithMany("Attens")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Log", b =>
                {
                    b.HasOne("SchoolManagement.Entities.Teacher", null)
                        .WithMany("Logs")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Teacher", b =>
                {
                    b.HasOne("SchoolManagement.Entities.UeserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountUeserAccountId");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Student", b =>
                {
                    b.Navigation("Attens");
                });

            modelBuilder.Entity("SchoolManagement.Entities.Teacher", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
